"""The helm bundle: the chart in templates/helm copied verbatim, plus a values
overlay built from the options.

The chart restates the generator's judgements in Go templates;
tests/helm_parity.py holds both formats to the same objects.
"""

import json
import os

from .bundle_env import DEFAULT_NO_PROXY, extra_env, proxy_env, proxy_has_creds
from .bundle_names import (CHART_DIR, HELM_DIR, HELM_VALUES_FILE,
                           MIRROR_SCRIPT_FILE, NODEPOOLS_FILE)
from .bundle_options import (auto_update, engine_scheduling, engine_size,
                             separate_pools, service_account)
from .ca_trust import CA_FILENAME, CA_MOUNT_PATH, ca_cfg
from .footprint import (ENGINE_DEFAULT_REQUEST_CPU,
                        ENGINE_DEFAULT_REQUEST_MEM, ENGINE_DISK_GB,
                        ENGINE_TMP_GB)
from .image_registry import crane_image, image_overrides, mirror_script
from .markers import helm_token_at_install
from .nodepools import nodepools_md
from .quantity import format_cpu, format_memory
from .quoting import yq
from .readme_parts import (bundle_table, ca_slot_block, deploy_steps,
                           ignored_block, location_bullet,
                           placeholder_block, requests_bullet, sa_bullet,
                           sizing_bullet,
                           sv_bullet, verify_block)
from .service_virt import SV_INGRESS_BACKENDS, sv_cfg


def _helm_chart_files():
    """The static chart, keyed by output path."""
    out = {}
    for root, _, names in os.walk(HELM_DIR):
        for name in sorted(names):
            rel = os.path.relpath(os.path.join(root, name), HELM_DIR)
            with open(os.path.join(root, name)) as f:
                out[f"{CHART_DIR}/{rel}"] = f.read()
    return out


def _helm_values(facts, o):
    """The values overlay: the resolved options in the chart's vocabulary.

    Written as text because it is a file people read and edit, and its comments
    are the point. Keys left at the chart's default are written only where they
    record a choice.
    """
    ca = ca_cfg(o)
    image = crane_image(facts, o)
    repo, _, tag = image.rpartition(":")
    lines = [
        "# BlazeMeter private location agent -- generated by bzm-opl-gen from",
        f"# location {facts.get('harbor_name') or facts['harbor_id']} ({facts['harbor_id']}).",
        "#",
        f"#   helm install crane ./{CHART_DIR} -n {o['namespace']} -f {HELM_VALUES_FILE}",
        "#",
        "# Values for this location; anything not set here keeps the chart's",
        "# default (`helm show values ./helm`). Re-generating overwrites this file.",
        "",
        f"harborId: {yq(facts['harbor_id'])}",
        f"shipId: {yq(o['ship_id'])}",
    ]
    if not helm_token_at_install(o):
        lines += [
            "# The agent credential. Do not commit it; alternatively pass it with",
            "# --set-string authToken=... or use existingSecret.",
            f"authToken: {yq(o['auth_token'])}",
        ]
    else:
        lines += [
            "# Pass it at install time: helm install --set-string authToken=...",
            'authToken: ""',
        ]
    lines += [
        "",
        f"platform: {o['platform']}",
        f"serviceType: {o['service_type']}",
    ]
    if not o["restrict_engines"]:
        lines += [
            "# Engines run with crane's default (privileged) security context,",
            "# which restricted PodSecurity, OpenShift SCC and GKE Autopilot refuse.",
            "restrictEngines: false",
        ]
    lines += [
        f"useSecret: {'true' if o['use_secret'] else 'false'}",
        'existingSecret: ""',
        "",
        "image:",
        "  # The version this location advertised when this file was generated.",
        f"  repository: {yq(repo)}",
        f"  tag: {yq(tag)}",
        "  pullPolicy: Always",
        f"  pullSecret: {yq(o['pull_secret'] or '')}",
        "",
    ]
    if o["private_registry"]:
        overrides = image_overrides(facts, o)
        lines += [
            f"privateRegistry: {yq(o['private_registry'])}",
            f"# Images from: {facts.get('images_source', 'unknown')}. Re-generate",
            "# rather than editing by hand; bzm-opl-image-mirror.sh pushes these.",
            "imageOverrides:",
        ] + [f"  {json.dumps(k)}: {yq(v)}" for k, v in sorted(overrides.items())] + [
            f"registryAuth: {'true' if o['registry_auth'] else 'false'}",
        ]
    else:
        lines += [
            "# Empty -> BlazeMeter's public registry.",
            'privateRegistry: ""',
            "imageOverrides: {}",
            "registryAuth: false",
        ]
    if o["crane_hook"]:
        lines += [
            "",
            "# crane-hook cluster check; run it with `helm test <release>`.",
            "craneHook:",
            "  enabled: true",
        ]
    if o["auto_update"] is None:
        lines += [
            "",
            "# Unset is off: `helm upgrade` works normally, and you keep the agent",
            "# current by bumping image.tag. See autoUpdate in the chart's values.yaml.",
            "autoUpdate:",
        ]
    else:
        lines += [
            "",
            ("# On: crane updates its own Deployment, so `helm upgrade` conflicts\n"
             "# and changes need uninstall + install. See autoUpdate in the\n"
             "# chart's values.yaml."
             if o["auto_update"] else
             "# Off: Helm manages the Deployment; keep the agent current by\n"
             "# bumping image.tag."),
            f"autoUpdate: {'true' if o['auto_update'] else 'false'}",
        ]
    lines += [
        "",
        f"clusterRbac: {'true' if o['cluster_rbac'] else 'false'}",
        "# The account crane runs as. With create: false it must already exist.",
        "serviceAccount:",
        f"  create: {'true' if o['service_account_create'] else 'false'}",
        f"  name: {yq(service_account(o))}",
        "  annotations: {}",
        "",
    ]
    if o["platform"] == "openshift":
        lines += ["# Ignored on openshift: the SCC assigns the UID.",
                  f"runAsUser: {o['run_as_user']}"]
    else:
        lines.append(f"runAsUser: {o['run_as_user']}")
    lines.append("")
    if o["node_selector"]:
        lines += ["nodeSelector:"] + [
            f"  {json.dumps(k)}: {yq(v)}" for k, v in o["node_selector"].items()]
    else:
        lines.append("nodeSelector: {}")
    if o["tolerations"]:
        lines.append("tolerations:")
        for tol in o["tolerations"]:
            items = list(tol.items())
            lines += [f"  {'- ' if i == 0 else '  '}{k}: {yq(v)}"
                      for i, (k, v) in enumerate(items)]
    else:
        lines.append("tolerations: []")

    # Always the effective engine placement: the chart cannot tell unset from
    # explicitly empty once the file is written.
    eng_sel, eng_tol = engine_scheduling(o)
    lines.append("")
    if separate_pools(o):
        lines.append("# Engines run on their own node pool; see nodepools.md.")
    else:
        lines.append("# Engines use the same placement as crane.")
    if eng_sel:
        lines += ["engineNodeSelector:"] + [
            f"  {json.dumps(k)}: {yq(v)}" for k, v in eng_sel.items()]
    else:
        lines.append("engineNodeSelector: {}")
    if eng_tol:
        lines.append("engineTolerations:")
        for tol in eng_tol:
            items = list(tol.items())
            lines += [f"  {'- ' if i == 0 else '  '}{k}: {yq(v)}"
                      for i, (k, v) in enumerate(items)]
    else:
        lines.append("engineTolerations: []")
    cpu_limit, mem_limit = engine_size(o)
    lines += [
        "",
        "# Engine pod limits. Empty: the chart default. This location's engines",
        f"# need {format_cpu(cpu_limit)} CPU + {format_memory(mem_limit)} each, plus ~{ENGINE_DISK_GB}GB disk ({ENGINE_TMP_GB}GB of it /tmp).",
        "#",
        "# Engine requests are not settable here: they come from the location's",
        "# overrideCPU/overrideMemory (default "
        f"{ENGINE_DEFAULT_REQUEST_CPU}/{ENGINE_DEFAULT_REQUEST_MEM}). Set them to match",
        "# these limits; README.md has the command.",
        "engine:",
        f"  cpuLimit: {yq(o['engine_cpu_limit'] or '')}",
        f"  memoryLimit: {yq(o['engine_mem_limit'] or '')}",
        f"  ephemeralRequestMb: {yq(o['engine_ephemeral_request_mb'] or '')}",
        f"  ephemeralLimitMb: {yq(o['engine_ephemeral_limit_mb'] or '')}",
    ]
    # Request and limit together: Autopilot collapses any gap between them.
    if o["crane_ephemeral_storage"]:
        lines += [
            "",
            "# Crane's own pod. Keep request and limit equal: GKE Autopilot",
            "# lowers the limit to the request.",
            "crane:",
            "  resources:",
            "    requests:",
            f"      ephemeral-storage: {yq(o['crane_ephemeral_storage'])}",
            "    limits:",
            f"      ephemeral-storage: {yq(o['crane_ephemeral_storage'])}",
        ]
    sv = sv_cfg(facts, o)
    if sv:
        backend = SV_INGRESS_BACKENDS[sv["type"]]
        lines += [
            "",
            "# Service virtualization: crane publishes one "
            f"{backend.creates} per virtual",
            "# service, at <virtual-service>-<port>-<namespace>.<subdomain>.",
            "sv:",
            f"  ingress: {yq(sv['type'])}",
            f"  subdomain: {yq(sv['subdomain'])}",
            "  # Required even for HTTP virtual services. Create it in this",
            "  # namespace; this bundle does not."
            if backend.tls_secret_read else
            "  # Required even for HTTP virtual services. This backend does not"
            "\n  # read it, so the Secret need not exist.",
            f"  tlsSecret: {yq(sv['tls_secret'])}",
        ]
        if sv["type"] == "istio":
            lines.append(
                f"  # Crane uses this Gateway for every virtual service.\n"
                f"  istioGateway: {yq(sv['istio_gateway'])}"
                if sv["istio_gateway"] else
                "  # Empty: crane creates a Gateway per virtual service.\n"
                '  istioGateway: ""')
    lines.append("")
    if o["proxy"]:
        env = proxy_env(o)
        lines += ["proxy:", "  enabled: true"]
        if proxy_has_creds(o):
            lines.append("  # Credentials are in the URL; the chart stores such a URL in the Secret.")
        lines += [
            f"  http: {yq(env.get('HTTP_PROXY', ''))}",
            f"  https: {yq(env.get('HTTPS_PROXY', ''))}",
            f"  noProxy: {yq(env['NO_PROXY'])}",
        ]
    else:
        lines += ["proxy:", "  enabled: false", '  http: ""', '  https: ""',
                  f"  noProxy: {yq(DEFAULT_NO_PROXY)}"]
    lines.append("")
    # The certificate never enters the overlay: the chart reads it from a file
    # in the chart directory at install time, which the bundle ships when it
    # has the PEM.
    mode = {"inline": "inline", "file": "inline", "existing": "existing",
            "inject": "openshiftInject"}[ca["mode"]] if ca else "none"
    lines += ["caBundle:", f"  mode: {mode}"]
    if ca and ca["mode"] in ("inline", "file"):
        lines += [
            '  pem: ""',
            "  # The certificate file, beside helm/Chart.yaml.",
            f"  file: {yq(ca['key'])}",
        ]
    else:
        lines += ['  pem: ""', '  file: ""']
    lines += [
        f"  existingConfigMap: {yq(ca['cm'] if ca and ca['mode'] == 'existing' else '')}",
        f"  key: {yq(ca['key'] if ca else CA_FILENAME)}",
        f"  mountPath: {yq(CA_MOUNT_PATH)}",
    ]
    env = extra_env(o)
    if env:
        lines += [
            "",
            "# Additional agent variables. They reach crane, not the engines.",
            "extraEnv:",
        ] + [f"  {json.dumps(k)}: {yq(v)}" for k, v in env.items()]
    return "\n".join(lines) + "\n"


def _upgrade_bullet(o):
    """What `helm upgrade` does to this overlay: it fails on a conflict only
    where auto-update was asked for.
    """
    if auto_update(o):
        return (f"- **Upgrading:** this bundle asked for auto-update, so crane "
                f"owns its own\n  Deployment and `helm upgrade` fails on a "
                f"conflict. Change things by\n  reinstalling, or set "
                f"`autoUpdate: false` in `{HELM_VALUES_FILE}` and reinstall "
                f"once.")
    return ("- **Upgrading:** `helm upgrade` works as it should -- auto-update "
            "is off, so\n  Helm is the only writer of the Deployment. Keeping "
            "the agent current is\n  your job: bump `image.tag` and upgrade "
            "(an agent far behind loses support).")


def _helm_readme(facts, o):
    """README.md for the helm bundle: instructions only; the chart's own README
    carries the reasoning.
    """
    ns = o["namespace"]
    token = ""
    if helm_token_at_install(o):
        # A sample value is lower case; `<AUTH_TOKEN>` would match
        # MARKER_PATTERN and read as an unfinished field.
        token = (" \\\n    --set-string authToken=<token>"
                 "   # not in the values file;\n    # re-generate with "
                 "--auth-token <token> to embed it")
    return f"""{bundle_table(facts, o)}{placeholder_block(facts, o)}{ca_slot_block(o)}
## Deploy

{deploy_steps(o, "Install")}```
helm install crane ./{CHART_DIR} -n {ns} --create-namespace -f {HELM_VALUES_FILE}{token}
```

{verify_block(o)}
## Worth knowing

{sizing_bullet(facts, o)}{location_bullet(facts, o)}{sa_bullet(o)}{sv_bullet(facts, o)}
{requests_bullet(facts, o)}
{_upgrade_bullet(o)}
- `{HELM_VALUES_FILE}` holds everything specific to you; `{CHART_DIR}/` is the same
  chart for everyone. `helm show values ./{CHART_DIR}` lists every option.
{ignored_block(o)}"""


def render(facts, o, ca):
    """The helm bundle as {filename: content}, profile.json aside."""
    out = _helm_chart_files()
    out[HELM_VALUES_FILE] = _helm_values(facts, o)
    # `caBundle.file` is read with .Files.Get, which reaches only the chart
    # directory. The file mode ships nothing, and the chart refuses the install.
    if ca and ca["mode"] == "inline":
        out[f"{CHART_DIR}/{ca['key']}"] = o["ca_bundle"].strip() + "\n"
    if o["private_registry"]:
        out[MIRROR_SCRIPT_FILE] = mirror_script(facts, o)
    if separate_pools(o):
        out[NODEPOOLS_FILE] = nodepools_md(facts, o)
    out["README.md"] = _helm_readme(facts, o)
    return out
